{
 "title": "API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Visão Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de Atividade do Processo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Requisições por Endpoint e Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (endpoint, http_status) (rate(flask_api_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Desempenho",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latência das Requisições",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(flask_api_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requisições Lentas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(flask_api_request_duration_seconds_bucket{le=\"0.5\"}[5m])) by (endpoint)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Somatório",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(flask_api_request_duration_seconds_sum[5m])) / sum(rate(flask_api_request_duration_seconds_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Erros e Alertas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requisições com Erro",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(flask_api_requests_total{http_status=~\"4..|5..\"}[5m])) by (http_status, endpoint)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Número de Coletas promql Copiar código",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(python_gc_collections_total[5m])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Objetos Coletados por Geração",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "python_gc_objects_collected_total {job=\"flask-api\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Detalhes Técnicos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limites de Descritores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "process_open_fds / process_max_fds",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Versão do Python",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      { "expr": "python_info\n", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}